/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Charts: typeof import('./src/components/Charts/Charts.vue')['default']
    Cover: typeof import('./src/components/common/Cover/Cover.vue')['default']
    Dialog: typeof import('./src/components/common/Dialog/Dialog.vue')['default']
    Fluorescence: typeof import('./src/components/common/Fluorescence/Fluorescence.vue')['default']
    ToolItem: typeof import('./src/components/common/ToolItem/ToolItem.vue')['default']
  }
}
